//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OTEntities : DbContext
    {
        public OTEntities()
            : base("name=OTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<OT_APP1> OT_APP1 { get; set; }
        public DbSet<OT_APP2> OT_APP2 { get; set; }
        public DbSet<OT_APP3> OT_APP3 { get; set; }
        public DbSet<OT_APP4> OT_APP4 { get; set; }
        public DbSet<OT_AUDIT> OT_AUDIT { get; set; }
        public DbSet<OT_CYCLE> OT_CYCLE { get; set; }
        public DbSet<OT_CYCLE_PAYFILE> OT_CYCLE_PAYFILE { get; set; }
        public DbSet<OT_EMP> OT_EMP { get; set; }
        public DbSet<OT_OFFSET> OT_OFFSET { get; set; }
        public DbSet<OT_ORG> OT_ORG { get; set; }
        public DbSet<OT_POSITION> OT_POSITION { get; set; }
        public DbSet<OT_SHIFT> OT_SHIFT { get; set; }
        public DbSet<OT_TYPE> OT_TYPE { get; set; }
        public DbSet<OT_WORK> OT_WORK { get; set; }
        public DbSet<OT_WORK_OFFSET> OT_WORK_OFFSET { get; set; }
        public DbSet<SYS_SEQ> SYS_SEQ { get; set; }
    }
}
