//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_EMP
    {
        public OT_EMP()
        {
            this.OT_AUDIT = new HashSet<OT_AUDIT>();
            this.OT_OFFSET = new HashSet<OT_OFFSET>();
            this.OT_POSITION = new HashSet<OT_POSITION>();
            this.OT_WORK = new HashSet<OT_WORK>();
        }
    
        public string EMP_ID { get; set; }
        public string USER_ID { get; set; }
        public string EMP_NAME { get; set; }
        public string EMP_NUMBER { get; set; }
        public string EMP_SEX { get; set; }
        public Nullable<System.DateTime> EMP_START_DATE { get; set; }
        public string EMP_MAIL { get; set; }
        public Nullable<System.DateTime> EMP_LEAVE_DATE { get; set; }
        public string EMP_GRADE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public decimal VERSION_NUM { get; set; }
    
        public virtual ICollection<OT_AUDIT> OT_AUDIT { get; set; }
        public virtual ICollection<OT_OFFSET> OT_OFFSET { get; set; }
        public virtual ICollection<OT_POSITION> OT_POSITION { get; set; }
        public virtual ICollection<OT_WORK> OT_WORK { get; set; }
    }
}
