//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_ORG
    {
        public OT_ORG()
        {
            this.OT_APP1 = new HashSet<OT_APP1>();
            this.OT_APP2 = new HashSet<OT_APP2>();
            this.OT_APP3 = new HashSet<OT_APP3>();
            this.OT_OFFSET = new HashSet<OT_OFFSET>();
            this.OT_POSITION = new HashSet<OT_POSITION>();
            this.OT_WORK = new HashSet<OT_WORK>();
        }
    
        public string ORG_ID { get; set; }
        public int ORG_NUM { get; set; }
        public string ORG_NAME { get; set; }
        public string SIMPLE_NAME { get; set; }
        public string PARANT_ORG { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int VERSION_NUM { get; set; }
        public string OLEVEL { get; set; }
    
        public virtual ICollection<OT_APP1> OT_APP1 { get; set; }
        public virtual ICollection<OT_APP2> OT_APP2 { get; set; }
        public virtual ICollection<OT_APP3> OT_APP3 { get; set; }
        public virtual ICollection<OT_OFFSET> OT_OFFSET { get; set; }
        public virtual ICollection<OT_POSITION> OT_POSITION { get; set; }
        public virtual ICollection<OT_WORK> OT_WORK { get; set; }
    }
}
