//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_OFFSET
    {
        public OT_OFFSET()
        {
            this.OT_WORK_OFFSET = new HashSet<OT_WORK_OFFSET>();
        }
    
        public string OFFSET_ID { get; set; }
        public string OFFSET_NO { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> OFFSET_TIME { get; set; }
        public Nullable<System.DateTime> OFFSET_DATE { get; set; }
        public string EMP_ID { get; set; }
        public string ORG_ID { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int VERSION_NUM { get; set; }
        public string APP3_ID { get; set; }
        public string OFFSET_REMARK { get; set; }
    
        public virtual OT_APP3 OT_APP3 { get; set; }
        public virtual OT_EMP OT_EMP { get; set; }
        public virtual OT_ORG OT_ORG { get; set; }
        public virtual ICollection<OT_WORK_OFFSET> OT_WORK_OFFSET { get; set; }
    }
}
