//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Importer
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT_SHIFT
    {
        public OT_SHIFT()
        {
            this.OT_WORK = new HashSet<OT_WORK>();
        }
    
        public string SHIFT_ID { get; set; }
        public Nullable<short> SEQ_ID { get; set; }
        public string SHIFT_NAME { get; set; }
        public string STATUS { get; set; }
        public decimal OT_TIME { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public int VERSION_NUM { get; set; }
        public string OT_STYLE { get; set; }
        public string OT_FIX { get; set; }
    
        public virtual ICollection<OT_WORK> OT_WORK { get; set; }
    }
}
